--ДЗ по sql (база AVIA)
--1
SELECT MODEL, AIRCRAFT_CODE FROM LANIT.AIRCRAFTS_DATA ad
WHERE AIRCRAFT_CODE IN ('320','321','733')

--2
SELECT MODEL, AIRCRAFT_CODE FROM LANIT.AIRCRAFTS_DATA ad
WHERE AIRCRAFT_CODE NOT LIKE '3%'

--3
SELECT TICKET_NO, PASSENGER_NAME, EMAIL FROM LANIT.TICKETS t
WHERE t.PASSENGER_NAME LIKE 'OLGA%'
AND (EMAIL LIKE '%olga%' OR EMAIL = NULL)

--4.
SELECT MODEL FROM LANIT.AIRCRAFTS_DATA ad 
WHERE "RANGE" IN ('5600', '5700') ORDER BY ad."RANGE" DESC

--5.
SELECT AIRPORT_NAME, CITY FROM LANIT.AIRPORTS_DATA ad 
WHERE CITY = 'Moscow' 
ORDER BY ad.AIRPORT_NAME

--6.
SELECT DISTINCT CITY, TIMEZONE FROM LANIT.AIRPORTS_DATA ad 
WHERE ad.TIMEZONE LIKE 'Europe/%'

--7.
SELECT TOTAL_AMOUNT - (TOTAL_AMOUNT * 0.1) FROM LANIT.BOOKINGS b 
WHERE b.BOOK_REF LIKE '3A4%'

--8.
SELECT 'A place data: ' || SEAT_NO AS PlaceData FROM
LANIT.SEATS s WHERE AIRCRAFT_CODE = '320' AND FARE_CONDITIONS = 'Business'

--9.
SELECT MAX(TOTAL_AMOUNT), MIN(TOTAL_AMOUNT) FROM LANIT.BOOKINGS b WHERE TO_CHAR(BOOK_DATE,'yyyy')= '2017'

--10.
SELECT MODEL, COUNT(SEAT_NO) FROM LANIT.SEATS s 
INNER JOIN LANIT.AIRCRAFTS_DATA ad ON s.AIRCRAFT_CODE = ad.AIRCRAFT_CODE
GROUP BY ad.MODEL

--11.
SELECT MODEL, FARE_CONDITIONS, COUNT(SEAT_NO) FROM LANIT.SEATS s 
INNER JOIN LANIT.AIRCRAFTS_DATA ad ON s.AIRCRAFT_CODE = ad.AIRCRAFT_CODE
GROUP BY ad.MODEL, s.FARE_CONDITIONS

--12.
SELECT COUNT(TICKET_NO) FROM LANIT.TICKETS t WHERE PASSENGER_NAME ='ALEKSANDR STEPANOV' AND PHONE LIKE '%11'

--13.
SELECT PASSENGER_NAME, COUNT(TICKET_NO) FROM LANIT.TICKETS t WHERE t.PASSENGER_NAME LIKE 'ALEKSANDR%' GROUP BY PASSENGER_NAME HAVING COUNT(TICKET_NO) > '2000' ORDER BY COUNT(TICKET_NO) DESC

--14.
SELECT TRUNC(SCHEDULED_DEPARTURE, 'DD') FROM LANIT.FLIGHTS f WHERE TO_CHAR(f.SCHEDULED_DEPARTURE, 'yyyy-mm') = '2017-09' GROUP BY TRUNC(SCHEDULED_DEPARTURE, 'DD') HAVING COUNT(FLIGHT_NO) > '500'

--15
SELECT CITY, COUNT(AIRPORT_CODE)FROM LANIT.AIRPORTS_DATA ad
GROUP BY CITY HAVING COUNT(AIRPORT_CODE) > 1

--16.
SELECT MODEL, LISTAGG(AIRCRAFT_CODE, ', ') WITHIN GROUP (ORDER BY AIRCRAFT_CODE) "Place List"
FROM LANIT.AIRCRAFTS_DATA ad GROUP BY MODEL

--17
SELECT * FROM LANIT.AIRPORTS_DATA ad JOIN LANIT.FLIGHTS f
ON ad.AIRPORT_CODE = f.DEPARTURE_AIRPORT WHERE ad.CITY = 'Moscow'
AND TO_CHAR(f.SCHEDULED_DEPARTURE , 'yyyy-mm') = '2017-09'

--18
SELECT DEPARTURE_AIRPORT, COUNT(FLIGHT_NO) FROM LANIT.FLIGHTS f
JOIN LANIT.AIRPORTS_DATA ad ON ad.AIRPORT_CODE = f.DEPARTURE_AIRPORT
WHERE CITY = 'Moscow'
AND TO_CHAR(SCHEDULED_DEPARTURE, 'yyyy') = '2017' GROUP BY DEPARTURE_AIRPORT

--19
SELECT DEPARTURE_AIRPORT, TO_CHAR(SCHEDULED_DEPARTURE, 'yyyy-mm'), COUNT(FLIGHT_NO)
FROM LANIT.FLIGHTS f JOIN LANIT.AIRPORTS_DATA ad ON f.DEPARTURE_AIRPORT = ad.AIRPORT_CODE
WHERE CITY = 'Moscow'
AND TO_CHAR(SCHEDULED_DEPARTURE, 'yyyy') = '2017'
GROUP BY DEPARTURE_AIRPORT, TO_CHAR(SCHEDULED_DEPARTURE, 'yyyy-mm')

--20.
SELECT TICKET_NO, BOOK_REF FROM LANIT.TICKETS t WHERE BOOK_REF LIKE '3A4B%'

--21.
SELECT FLIGHT_NO, BOOK_REF FROM LANIT.TICKETS t 
JOIN LANIT.TICKET_FLIGHTS tf ON t.TICKET_NO = tf.TICKET_NO 
JOIN LANIT.FLIGHTS f ON tf.FLIGHT_ID = f.FLIGHT_ID 
WHERE t.BOOK_REF LIKE '3A4B%'
